name: KinD Cluster Setup

on:
  push:
    branches:
      - main

jobs:
  setup-kind-cluster:
    runs-on: ubuntu-latest


    steps:
      - name: Checking the repository
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind-cluster

      - name: Get Cluster Info
        run: kubectl cluster-info --context kind-kind-cluster

      - name: Check number of nodes
        run: kubectl get nodes

      - name: List all pods in the cluster
        run: kubectl get pods -A
